helmCharts:
  - name: bpmn-chart-2
    valuesFile: kustomize/values.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: camundacloud/camunda-demo
  newName: asia-southeast2-docker.pkg.dev/bravo-project-nonprod/bpm-docker
  newTag: 3410fe6
