spring-boot-http:
  image:
    name: "camundacloud/camunda-demo"
    pullPolicy: IfNotPresent

  nameOverride: "bpmn-demo-2"
  fullnameOverride: "bpmn-demo-2"

  health:
    liveness:
      port: 8080
      path: /engine-rest/engine
    readiness:
      port: 8080
      path: /engine-rest/engine