apiVersion: container.gcp.crossplane.io/v1beta2
kind: Cluster
metadata:
  name: app-cluster-test
spec:
  forProvider:
    location: asia-southeast1
    autopilot:
      enabled: false
    network: vpc-app-test-cluster
    subnetwork: vpc-app-cluster-test-subnet
    initialClusterVersion: latest
    ipAllocationPolicy:
      clusterSecondaryRangeName: vpc-app-cluster-test-pods
      servicesSecondaryRangeName: vpc-app-cluster-test-services	

---

apiVersion: container.gcp.crossplane.io/v1beta1
kind: NodePool
metadata:
  name: app-node-pool-test
spec:
  forProvider:
    autoscaling:
      enabled: true
      maxNodeCount: 3
      minNodeCount: 1
    initialNodeCount: 1
    locations:
    - asia-southeast1-b
    # - asia-southeast1-b
    # - asia-southeast1-c
    clusterRef:
      name: app-cluster-test
    maxPodsConstraint:
      maxPodsPerNode: 100