apiVersion: container.gcp.crossplane.io/v1beta2
kind: Cluster
metadata:
  name: app-cluster-test
spec:
  forProvider:
    location: asia-southeast1
    autopilot:
      enabled: false
    networkRef:
      name: vpc-bravo-project-nonprod
    initialClusterVersion: latest

---

apiVersion: container.gcp.crossplane.io/v1beta1
kind: NodePool
metadata:
  name: app-node-pool-test
spec:
  forProvider:
    autoscaling:
      enabled: true
      maxNodeCount: 1
      minNodeCount: 3
    initialNodeCount: 1
    locations:
    - asia-southeast1-a
    # - asia-southeast1-b
    # - asia-southeast1-c
    clusterRef:
      name: app-cluster-test
    maxPodsConstraint:
      maxPodsPerNode: 100